name = "SampleArrays"
uuid = "740e20ac-97ea-4c00-b3fe-fb313cfcaca0"
authors = ["Michael Schilling <21343359+Ntropic@users.noreply.github.com>"]
version = "0.1.1"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
